import type { SupportedLocale } from '../types'
const en = {
  title: 'Grading center', mode: 'Grading mode', single: 'Single paper', batch: 'Batch grading', chat: 'Chat', dependency: 'Enable Scanner before using paper grading.', chatHint: 'Put the paper under the camera on the right, then talk to the agent to grade it.', ocrResult: 'Recognized content',
  class: 'Class', exam: 'Exam', create: 'Create', name: 'Name', rubric: 'Answer key and scoring rubric', import: 'Add images', folder: 'Add folder', drop: 'Drop images or a folder here', camera: 'Open camera', capture: 'Capture', close: 'Close camera', start: 'Start grading', pause: 'Pause after current papers', retry: 'Retry', review: 'Teacher review required', pdf: 'Export PDF', png: 'Export PNG', report: 'Export class report', allPdf: 'Export all PDF', settings: 'Model settings', ocrModel: 'OCR model', model: 'Grading model', threshold: 'Review threshold', save: 'Save', rough: 'Hand drawn', printed: 'Printed', undo: 'Undo', redo: 'Redo', pen: 'Pen', circle: 'Circle', comment: 'Comment', badge: 'Score label', select: 'Select / drag', remove: 'Delete annotation', text: 'Annotation text', loading: 'Processing…', empty: 'Choose an exam and add papers to begin.', average: 'Average', max: 'Highest', min: 'Lowest', passRate: 'Pass rate', pending: 'Pending', ocr: 'OCR', recognized: 'Recognized', detected: 'Questions detected', grading: 'Grading', graded: 'Graded', done: 'Done', error: 'Error', saved: 'Saved', rubricRequired: 'Enter an answer key and scoring rubric first.', exportHint: 'Export includes the current annotations. AI results should be reviewed before sharing.', color: 'Pen color', width: 'Pen width', newClass: 'New class', newExam: 'New exam', failed: 'Action failed', student: 'Student name', wrongRank: 'Most missed questions', confirmReview: 'Mark reviewed',
}
const zh: typeof en = {
  title: '批改中心', mode: '批改模式', single: '批改单张', batch: '批量批改', chat: '普通对话', dependency: '请先开启扫描插件，再使用批改插件。', chatHint: '把试卷放到右侧摄像头下，然后像对话一样告诉 Agent 批改。', ocrResult: '识别内容',
  class: '班级', exam: '考试', create: '新建', name: '名称', rubric: '参考答案与评分标准', import: '添加图片', folder: '添加文件夹', drop: '拖入图片或文件夹', camera: '打开摄像头', capture: '拍照加入队列', close: '关闭摄像头', start: '开始批改', pause: '完成当前作业后暂停', retry: '重试', review: '需要老师复核', pdf: '导出 PDF', png: '导出 PNG', report: '导出班级报表', allPdf: '导出全部 PDF', settings: '模型设置', ocrModel: 'OCR 模型', model: '评分模型', threshold: '复核阈值', save: '保存', rough: '手绘风', printed: '印刷风', undo: '撤销', redo: '重做', pen: '画笔', circle: '圈选', comment: '评语', badge: '分数标签', select: '选择 / 拖动', remove: '删除批注', text: '批注文字', loading: '处理中…', empty: '选择考试并添加试卷，即可开始批改。', average: '平均分', max: '最高分', min: '最低分', passRate: '及格率', pending: '待处理', ocr: '识别中', recognized: '已识别', detected: '已分题', grading: '评分中', graded: '已评分', done: '完成', error: '错误', saved: '已保存', rubricRequired: '请先填写参考答案与评分标准。', exportHint: '导出包含当前批注，分享前请复核 AI 评分。', color: '笔色', width: '粗细', newClass: '新建班级', newExam: '新建考试', failed: '操作失败', student: '学生姓名', wrongRank: '错题排行', confirmReview: '确认已复核',
}
export const messages: Record<SupportedLocale, typeof en> = { en, zh, 'zh-TW': { ...zh, title: '批改中心', single: '批改單張', batch: '批次批改', save: '儲存' }, ar: { ...en, title: 'مركز التصحيح' }, de: { ...en, title: 'Korrekturzentrum' }, es: { ...en, title: 'Centro de corrección' }, fr: { ...en, title: 'Centre de correction' }, ja: { ...en, title: '採点センター' }, ko: { ...en, title: '채점 센터' }, pt: { ...en, title: 'Central de correção' }, ru: { ...en, title: 'Центр проверки' } }
